### ISSUE TITLE
Mysterious "enabled" setting ?

### ISSUE THREAD

**Issue by SuperCVL** [Tassadar921/Tassadraft-v2#12]
![chrome_hcWlmB54Eb](https://github.com/user-attachments/assets/81b6dfa4-b77f-4ea9-b965-89c7b096c6d7)

**Comment by Tassadar921** [comment]
Will be used in the future : a disabled deck won't use cards from our collection, an enabled one will automatically pick a maximum of available cards in some of our collections, or all of them, to tell us which cards lack in our collection to build the deck physically
